package main

import (
	"fmt"
	"sort"
	"strings"
)

// buildAwesomeReadme renders a Markdown README listing targets grouped by
// platform (sorted alphabetically), alphabetically by repo name within each
// group. Pure function — no I/O — so output can be asserted directly.
func buildAwesomeReadme(targets []GitLabSyncTarget) string {
	groups := map[string][]GitLabSyncTarget{}
	for _, t := range targets {
		groups[t.Platform] = append(groups[t.Platform], t)
	}
	var platforms []string
	for p := range groups {
		platforms = append(platforms, p)
	}
	sort.Strings(platforms)

	var b strings.Builder
	b.WriteString("# Awesome Repos\n\n")
	b.WriteString("Auto-generated by [newreleases](https://github.com/Harnish/newreleases). Do not edit by hand.\n\n")
	if len(platforms) == 0 {
		b.WriteString("_No synced repos yet._\n")
		return b.String()
	}
	for _, p := range platforms {
		items := groups[p]
		sort.Slice(items, func(i, j int) bool { return items[i].RepoName < items[j].RepoName })
		title := strings.ToUpper(p[:1]) + p[1:]
		b.WriteString(fmt.Sprintf("## %s\n\n", title))
		for _, t := range items {
			b.WriteString(fmt.Sprintf("- [%s](%s)\n", t.RepoName, t.RepoURL))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// syncAwesomePage regenerates and pushes the Awesome README for userID. A
// no-op returning nil if the user hasn't enabled the feature. A method (not
// a free function reading the global store) for the same reason as
// (*Store).syncProjectToGitLab — see that doc comment.
func (s *Store) syncAwesomePage(userID string) error {
	settings, err := s.GetGitLabSettings(userID)
	if err != nil {
		return err
	}
	if !settings.AwesomeEnabled {
		return nil
	}
	if settings.GitLabToken == "" {
		return fmt.Errorf("gitlab token not configured")
	}
	client := newGitLabClient(settings.GitLabURL, settings.GitLabToken)

	httpURL := settings.AwesomeGitLabPath
	if httpURL == "" {
		path := slugify(settings.AwesomeRepoName)
		exists, err := client.ProjectExists(path)
		if err != nil {
			return fmt.Errorf("check awesome project: %w", err)
		}
		if exists {
			httpURL, err = client.GetProjectHTTPURL(path)
		} else {
			httpURL, err = client.CreateProject(path)
		}
		if err != nil {
			return fmt.Errorf("create/get awesome project: %w", err)
		}
		if err := s.SetAwesomeGitLabPath(userID, httpURL); err != nil {
			return fmt.Errorf("save awesome project path: %w", err)
		}
	}

	pushURL, err := client.AuthenticatedPushURL(httpURL)
	if err != nil {
		return err
	}
	targets := s.GetUserGitLabSyncTargets(userID)
	content := buildAwesomeReadme(targets)
	return pushGeneratedContent(pushURL, map[string]string{"README.md": content})
}
